map_type: costmap
origin_z: 0.0
z_resolution: 1
z_voxels: 2

obstacle_range: 8
raytrace_range: 8

publish_voxel_map: false
transform_tolerance: 0.5
meter_scoring: true

footprint: [[-1.6, -1.6], [-1.6, 1.6], [1.6, 1.6], [1.6, -1.6]]
footprint_padding: 0.01

plugins:
  - { name: obstacles_layer, type: "costmap_2d::ObstacleLayer" }
  # Enable VoxelLayer to 'remember' past obstacles and save them in the global map
  # - {name: voxel_layer, type: "costmap_2d::VoxelLayer"}
  - { name: inflation_layer, type: "costmap_2d::InflationLayer" }

# obstacles_layer is configured in seperate file depending on enabled sensors

voxel_layer:
  publish_voxel_map: true
  observation_sources: scan1 scan2 scan3
  scan1:
    sensor_frame: camera_link_backhazcam_left
    data_type: LaserScan
    topic: "/curiosity_mars_rover/camera_backhazcam/scan"
    marking: true
    clearing: true
    inf_is_valid: true
    min_obstacle_height: -4
    max_obstacle_height: 4
  scan2:
    sensor_frame: camera_link_fronthazcam_left
    data_type: LaserScan
    topic: "/curiosity_mars_rover/camera_fronthazcam/scan"
    marking: true
    clearing: true
    inf_is_valid: true
    min_obstacle_height: -4
    max_obstacle_height: 4
  scan3:
    sensor_frame: camera_link_navcam_left
    data_type: LaserScan
    topic: "/curiosity_mars_rover/camera_navcam/scan"
    marking: true
    clearing: true
    inf_is_valid: true
    min_obstacle_height: -4
    max_obstacle_height: 4

# Inflation layer is used to create a radius of space to avoid around each obstacle
inflation_layer:
  inflation_radius: 3.0
