obstacles_layer:
  observation_sources: scan1 scan2 scan3
  scan1:
    sensor_frame: camera_link_fronthazcam_left
    data_type: LaserScan
    topic: "/curiosity_mars_rover/camera_fronthazcam/scan"
    marking: true
    clearing: true
    inf_is_valid: true
  scan2:
    sensor_frame: camera_link_backhazcam_left
    data_type: LaserScan
    topic: "/curiosity_mars_rover/camera_backhazcam/scan"
    marking: true
    clearing: true
    inf_is_valid: true
  scan3:
    sensor_frame: camera_link_navcam_left
    data_type: LaserScan
    topic: "/curiosity_mars_rover/camera_navcam/scan"
    marking: true
    clearing: true
    inf_is_valid: true

  # Fake Depth PointCloud Sources
  # scan1: {sensor_frame: camera_link_backhazcam_left, data_type: PointCloud, topic: /curiosity_mars_rover/camera_backhazcam/depth/points, marking: true, clearing: true, min_obstacle_height: 0.2, max_obstacle_height: 4, obstacle_range: 4, raytrace_range: 3.0}
  # scan2: {sensor_frame: camera_link_fronthazcam_left, data_type: PointCloud, topic: /curiosity_mars_rover/camera_fronthazcam/depth/points, marking: true, clearing: true, min_obstacle_height: 0.2, max_obstacle_height: 4, obstacle_range: 4, raytrace_range: 3.0}
  # scan3: {sensor_frame: camera_link_navcam_left, data_type: PointCloud, topic: /curiosity_mars_rover/camera_navcam/depth/points, marking: true, clearing: true, min_obstacle_height: 1.2, max_obstacle_height: 4, obstacle_range: 2.5, raytrace_range: 3.0}
