global_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 20
  publish_frequency: 5
  width: 80.0
  height: 80.0
  resolution: 0.05
  origin_x: -40.0
  origin_y: -40.0
  static_map: true
  rolling_window: false
